# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HyunGG' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HyunGG
    pod 'Alamofire', '~> 5.2'
    pod 'ObjectMapper', '~> 3.5'
    pod "Texture"
    pod 'ReactorKit'
    pod "RxCocoa"

end
